### ISSUE TITLE
Heads up on new fork repo : https://github.com/jdonaldson/hx-lua-simdjson

### ISSUE THREAD

**Issue by jdonaldson** [FourierTransformer/lua-simdjson#13]
I just wanted to pass along the fork I made : https://github.com/jdonaldson/hx-lua-simdjson

I stripped it down from your original repo here.  I'm not going to maintain benchmarks, specs, etc. (I'll do that over in haxe-land).

I retained the license, and added you to the acknowledgements along with the simdjson authors.

Anything else I'm missing there?

FWIW, I think a fork wound up being the right call here for a lot of reasons.  I had to tweak things a lot to get them working properly for my Haxe target.  It'll be very difficult to unify our efforts here, unfortunately. :(

As a side note, I did resolve one json spec issue by updating the simdjson single header cpp/h files.  I'd do that at your earliest convenience to ensure you've got up to date json format compliance.

Cheers!

(close this whenever you're happy with it)

**Comment by FourierTransformer** [comment]
Glad to hear you got it working! I ended up putting in a simple PR (#14) that updates to the latest version at supports the newer JSON pointer implementation.
