### ISSUE TITLE
Makefile works incorrectly on non-windows platforms

### ISSUE THREAD

**Issue by tobil4sk** [FourierTransformer/lua-simdjson#78]
There is this warning given:
```
Warning: unmatched variable LUA_LIBDIR
```

`LUA_LIBDIR` is not defined on most platforms, see: https://github.com/luarocks/luarocks/issues/1257.

This means that the -L flag is empty here:
https://github.com/FourierTransformer/lua-simdjson/blob/f8248404e56f5b7a68da0f56f64ee798ae5b6462/Makefile#L3

So the following gets passed to the compiler: `-L -lpthread`, and `-lpthread` is incorrectly parsed as a search path. On clang this gives a warning that makes this problem more obvious:

```
ld: warning: search path '-lpthread' not found
```

See here for a possible patch from a fork:
https://github.com/Apprentice-Alchemist/hx-lua-simdjson/compare/e8370f1b3ad4f0642c480c2102fe3831d95b3d6d...main

**Comment by FourierTransformer** [comment]
Ah thanks for the notification and the PRs! I'll merge and test them over the next couple of days and try and get a release out! Also thanks for linking to the hx-lua-simdjson, they seem to have gotten the bindings working up to 3.8.0, so I might poke around there and see if I can get this version updated!

**Comment by tobil4sk** [comment]
You're welcome, and thanks for merging! It would be nice to have an upgrade to a newer version, I think it should also allow for mac arm64 support.

**Comment by FourierTransformer** [comment]
I've actually been working on getting simdjson 3.9.5 going and so far have the `parse` and `parseFile` methods working using the `ondemand` parser. I'm currently working on getting the `open` and JSON pointer functionality working. I'll try and push up the branch later today.
